import { AppProviders } from '@/app/providers/AppProviders'
import { AppRouter } from '@/app/router/AppRouter'
import { AuthProvider } from '@/context/AuthContext'
import './locales'
import './styles/index.css'

/**
 * Entry point (see d2.config.js). The legacy AuthProvider stays here, outside the
 * strict src/app folder, until it is removed at the end of Phase 8.
 *
 * `./locales` is generated by the platform (i18n/*.po -> src/locales) and registers the
 * translations with @dhis2/d2-i18n. It must be imported exactly once, here.
 */
const App = () => (
    <AppProviders>
        <AuthProvider>
            <AppRouter />
        </AuthProvider>
    </AppProviders>
)

export default App
