import { AppProviders } from '@/app/providers/AppProviders'
import { AppRouter } from '@/app/router/AppRouter'
import { SessionGate } from '@/features/auth'
import './locales'
import './styles/index.css'

/**
 * Entry point (see d2.config.js).
 *
 * `./locales` is generated by the platform (i18n/*.po -> src/locales) and registers the
 * translations with @dhis2/d2-i18n. It must be imported exactly once, here.
 */
const App = () => (
    <AppProviders>
        <SessionGate>
            <AppRouter />
        </SessionGate>
    </AppProviders>
)

export default App
